### ISSUE TITLE
Is there any way to change the theme ?

### ISSUE THREAD

**Issue by Hujjat** [wayou/HTML5_Audio_Visualizer#12]
Hi

Thank's for your great project. 

Is there any way to customize the wawes style?

**Comment by AlbyShure** [comment]
Within the JS file on lines 162, 163, 164 there should be a gradient. This is where the colors for the waves are. Just take out the #f00 #0f0 #0ff and put in whatever colors you'd like. @Hujjat

**Comment by wayou** [comment]
actually it's https://github.com/wayou/HTML5_Audio_Visualizer/blob/gh-pages/js/html5_audio_visualizer.js#L167-L170.
thx @AlbyShure anyway.

**Comment by Hujjat** [comment]
@AlbyShure @wayou Thank's. :)
