### ISSUE TITLE
播放录音问题

### ISSUE THREAD

**Issue by awtmeng** [wayou/HTML5_Audio_Visualizer#15]
我用webrtc录制的音频文件，录制过程中将blob格式的音频转码成ArrayBuffer，再去用相关代码绘制到canvas中，绘制结果是一条不动的蓝虚线，如果将录音文件保存下来，再通过上传文件的方式绘制，是正常的，请问一下，录音过程中怎么绘制呢？

**Comment by zhubinsheng** [comment]
> 我用webrtc录制的音频文件，录制过程中将blob格式的音频转码成ArrayBuffer，再去用相关代码绘制到canvas中，绘制结果是一条不动的蓝虚线，如果将录音文件保存下来，再通过上传文件的方式绘制，是正常的，请问一下，录音过程中怎么绘制呢？

可以分享你的代码吗？刚好要做类似的功能，感谢
