### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by loctauxphilippe** [wayou/HTML5_Audio_Visualizer#2]
Hello!
I'ld like to add your beautiful visualizer into my music player.
How to add the js file? I tried, but it doesn't work...
Could you show me how to do it please?
Thanks!

**Comment by wayou** [comment]
basically you need to read in the audio file first, then follow the flow from the `_start` method.

what have u tried?

**Comment by loctauxphilippe** [comment]
Oh! I've tried that about a couple of days ago... I don't remember...
It's fine! I asked a friend and he helped me!
Thanks anyway! It's a useful tool! ;-)
