### ISSUE TITLE
Not an Issue, a Thank! I used it in a video, if you wanna see

### ISSUE THREAD

**Issue by PenguinIsrael** [wayou/HTML5_Audio_Visualizer#3]
I needed a spectrum for my first musical video, which is, not the best as people can say (They said it's terrible, well "Ahaon said...) but I like it.

Here's a link of my song with your visualizer!
https://www.youtube.com/watch?v=wKKHBxED6yQ

Colors are matching to my channel :P

some questions, any way to make it a tool that convert the music file into a video one?
maybe a vlc plugin or kdenlive one? also colors setting or similars.

Anyway I like your work! Thank for letting me enjoy it!

**Comment by wayou** [comment]
cool,dude! 
I love the video u made.
I love cool things so I made this visualizer and am happy that u enjoy it.

not sure how to convert 2 video from audio. but if u wanna record the screen u can use QuickTime

**Comment by PenguinIsrael** [comment]
Why convert 2 videos? I dont understand
And does quicktime has your visualizer? or similars? if it does I may try run it with wine on linux

**Comment by wayou** [comment]
> some questions, any way to make it a tool that convert the music file into a video one?
> maybe a vlc plugin or kdenlive one? also colors setting or similars.

😆 actually I didn't get it

**Comment by PenguinIsrael** [comment]
OK :P So I used a plugin called "screencastify" on chrome, which recorded your html5 page.

I thought maybe you can improve it so instead of only showing the spectrum users could download it as a video.

**Comment by wayou** [comment]
Oh, I see. But this is out of the scope of a visualizer.

**Comment by PenguinIsrael** [comment]
haha ok
