### ISSUE TITLE
Could you a license?

### ISSUE THREAD

**Issue by albell** [wayou/HTML5_Audio_Visualizer#4]
"Feel free to use" is cool, but where I'm at, the folks in legal will want something more explicit. 😸 

Can you add an explicit MT license?

**Comment by wayou** [comment]
sure. but I don't have my laptop with me at present,if you can't wait, pull request is welcomed

**Comment by ebelliveau** [comment]
When all else fails, there's always the [WTFPL](http://www.wtfpl.net/) :)

**Comment by namnn89** [comment]
How to run Ios Safari. now it not working.?
