### ISSUE TITLE
一个细节的疑问

### ISSUE THREAD

**Issue by zhe-he** [wayou/HTML5_Audio_Visualizer#6]
188~191
`           var step = Math.round(array.length / meterNum); //sample limited data from the total array
            ctx.clearRect(0, 0, cwidth, cheight);
            for (var i = 0; i < meterNum; i++) {
                var value = array[i * step];
`
如果 array.length/meterNum == int, 刚好除尽，那么191行中的最后一个  i * step == meterNum，不能获取到最后一个值，是否需要做如下修改:

`           var step = Math.floor(array.length / meterNum); //sample limited data from the total array
            ctx.clearRect(0, 0, cwidth, cheight);
            for (var i = 0; i < meterNum; i++) {
                var value = array[i * step];
`

**Comment by wayou** [comment]
不会哦, 因为循环的条件是 i < meterNum，所以最后一个值是 (meterNum-1)*1，不会越界
